from app.models import db, Review

def seed_reviews():

    rev1 = Review( user_id=1, business_id=21, review="wow they cook for you here, I personally prefer to cook the meat myself though", rating=5)
    rev2 = Review( user_id=2, business_id=20, review="amazing service, amazing broth flavors, check out the dancing noodles", rating=4)
    rev3 = Review( user_id=3, business_id=19, review="sooo spicy , it hurts so goood", rating=3)
    rev4 = Review( user_id=4, business_id=18, review="a little overrated but good sushi overrall", rating=2)
    rev5 = Review( user_id=5, business_id=17, review="chill place to grab some japanese beer and feast on some quality japanese tapas", rating=1)
    rev6 = Review( user_id=6, business_id=16, review="great JBBQ, quality and quantity!", rating=2)
    rev7 = Review( user_id=7, business_id=15, review="amazing JBBQ, a little expensive though!", rating=3)
    rev8 = Review( user_id=8, business_id=14, review="my favorite AYCE kbbq place! the wagyu belly is soooo good", rating=4)
    rev9 = Review( user_id=9, business_id=13, review="very consistent drinks, I can always expect my drinks to taste the same no matter when I come here", rating=5)
    rev10 = Review( user_id=10, business_id=12, review="very unique flavors that actually taste good rather than just to be different", rating=4)
    rev11 = Review( user_id=11, business_id=11, review="soooo good, it's no wonder their pho is award winning", rating=3)
    rev12 = Review( user_id=12, business_id=10, review="the shack stack will always have a place in my heart", rating=2)
    rev13 = Review( user_id=13, business_id=9, review="great modern italian food in LA", rating=1)
    rev14 = Review( user_id=14, business_id=8, review="this place lives up to the hype and then some", rating=2)
    rev15 = Review( user_id=15, business_id=7, review="some of the best hong kong style mango desserts you will ever find", rating=3)
    rev16 = Review( user_id=16, business_id=6, review="if you can get past the 30 minute lines then the drinks here are great", rating=4)
    rev17 = Review( user_id=17, business_id=5, review="the spring rolls here have the most amazing texture", rating=5)
    rev18 = Review( user_id=18, business_id=4, review="one of the best authentic bowls of pho I have ever had", rating=3)
    rev19 = Review( user_id=19, business_id=3, review="best omakase in this affordable price point hands down!", rating=2)
    rev20 = Review( user_id=20, business_id=2, review="the fatty beef toro is so yummy!", rating=1)
    rev21 = Review( user_id=21, business_id=1, review="omg this is THE BEST hot chicken sandwich I have ever had in my life!!", rating=2)


    db.session.add(rev1)
    db.session.add(rev2)
    db.session.add(rev3)
    db.session.add(rev4)
    db.session.add(rev5)
    db.session.add(rev6)
    db.session.add(rev7)
    db.session.add(rev8)
    db.session.add(rev9)
    db.session.add(rev10)
    db.session.add(rev11)
    db.session.add(rev12)
    db.session.add(rev13)
    db.session.add(rev14)
    db.session.add(rev15)
    db.session.add(rev16)
    db.session.add(rev17)
    db.session.add(rev18)
    db.session.add(rev19)
    db.session.add(rev20)
    db.session.add(rev21)

    db.session.commit()

def undo_review():
    db.session.execute("TRUNCATE businesses RESTART IDENTITY CASCADE;")
    db.session.commit()
